In [ ]:
import requests
import bs4
import re
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


graph_JDM= nx.Graph()

config = {
'user': 'mirzapour',
'password': 'mehdim',
'host': 'karadoc.lirmm.fr',
'database': '05012019_rezojdm',
'raise_on_warnings': True
 }

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

# jdm_cursor.execute("SELECT * FROM nodes WHERE (type=1 or type=2) and weight>60 order by weight desc")
# df_JDM_nodes=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Name','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=1 order by weight desc")
# df_JDM_r_raff_sem=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=5 order by weight desc")
# df_JDM_r_syn=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=6 order by weight desc")
# df_JDM_r_isa=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=8 order by weight desc")
# df_JDM_r_hypo=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=15 order by weight desc")
# df_JDM_r_lieu=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=24 order by weight desc")
# df_JDM_r_agent_1=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=26 order by weight desc")
# df_JDM_r_agent=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])



x1=set(df_JDM_r_raff_sem["Source"].unique())
x2=set(df_JDM_r_raff_sem["Destination"].unique())
y1=x1.union(x2)

x1=set(df_JDM_r_syn["Source"].unique())
x2=set(df_JDM_r_syn["Destination"].unique())
y2=x1.union(x2)


x1=set(df_JDM_r_isa["Source"].unique())
x2=set(df_JDM_r_isa["Destination"].unique())
y3=x1.union(x2)


x1=set(df_JDM_r_hypo["Source"].unique())
x2=set(df_JDM_r_hypo["Destination"].unique())
y4=x1.union(x2)


x1=set(df_JDM_r_lieu["Source"].unique())
x2=set(df_JDM_r_lieu["Destination"].unique())
y5=x1.union(x2)


x1=set(df_JDM_r_agent_1["Source"].unique())
x2=set(df_JDM_r_agent_1["Destination"].unique())
y6=x1.union(x2)


x1=set(df_JDM_r_agent["Source"].unique())
x2=set(df_JDM_r_agent["Destination"].unique())
y7=x1.union(x2)

y8=y1.union(y2,y3,y4,y5,y6,y7)

z=set(df_JDM_nodes["ID"].unique())

for id in range(df_JDM_nodes.shape[0]):
    graph_JDM.add_node(df_JDM_nodes.iloc[id]["Name"])
    
    
# nx.write_gexf(graph_JDM, "graph_JDM.gexf")    

# nx.draw(graph_JDM, with_labels = True)
# plt.show()



jdm_db.close()

seed_nodes=list(z.intersection(y8))
seed_nodes.sort()

print(len(y8))
print(len(z))
print(len(z.intersection(y8)))

In [2]:
import requests
import bs4
import re
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


graph_JDM= nx.Graph()

config = {
'user': 'mirzapour',
'password': 'mehdim',
'host': 'karadoc.lirmm.fr',
'database': '05012019_rezojdm',
'raise_on_warnings': True
 }

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

# jdm_cursor.execute("SELECT * FROM nodes WHERE (type=1 or type=2) and weight>60 order by weight desc")
# df_JDM_nodes=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Name','Type','Weight'])
# df_JDM_nodes.to_excel("df_JDM_nodes.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=1 order by weight desc")
# df_JDM_r_raff_sem=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_raff_sem.to_excel("df_JDM_r_raff_sem.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=5 order by weight desc")
# df_JDM_r_syn=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_syn.to_excel("df_JDM_r_syn.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=6 order by weight desc")
# df_JDM_r_isa=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_isa.to_excel("df_JDM_r_isa.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=8 order by weight desc")
# df_JDM_r_hypo=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_hypo.to_excel("df_JDM_r_hypo.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=15 order by weight desc")
# df_JDM_r_lieu=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_lieu.to_excel("df_JDM_r_lieu.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=24 order by weight desc")
# df_JDM_r_agent_1=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_agent_1.to_excel("df_JDM_r_agent_1.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=26 order by weight desc")
# df_JDM_r_agent=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_agent.to_excel("df_JDM_r_agent.xlsx")

jdm_db.close()

In [85]:
import requests
import bs4
import re
import datetime
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


df_JDM_nodes=pd.read_excel("df_JDM_nodes.xlsx")
df_JDM_seed_words=pd.read_excel("List_of_Seed_Words_Top_30000.xlsx")
seedwords=list(df_JDM_seed_words["Nodes"])

df_JDM_r_raff_sem=pd.read_excel("df_JDM_r_raff_sem.xlsx")
df_JDM_r_syn=pd.read_excel("df_JDM_r_syn_84.xlsx")
df_JDM_r_isa=pd.read_excel("df_JDM_r_isa_230.xlsx")
df_JDM_r_hypo=pd.read_excel("df_JDM_r_hypo_120.xlsx")
df_JDM_r_lieu=pd.read_excel("df_JDM_r_lieu_60.xlsx")
df_JDM_r_agent_1=pd.read_excel("df_JDM_r_agent_1.xlsx")
df_JDM_r_agent=pd.read_excel("df_JDM_r_agent.xlsx")

In [161]:
from IPython.display import clear_output

def remove_non_related_rows_for_nodes(df_JDM_r_relation,seedwords):
    df_JDM_r_relation_=df_JDM_r_relation.copy()
    lenght=df_JDM_r_relation_.shape[0]
    for row in range(lenght):
        if (df_JDM_r_relation_.loc[row,"ID"] not in seedwords):
            df_JDM_r_relation_=df_JDM_r_relation_.drop(row,axis=0)
        print(row/lenght,"%")
        clear_output(wait=True)
    df_JDM_r_relation_=df_JDM_r_relation_.reset_index(drop=True)
    return(df_JDM_r_relation_)


def remove_non_related_rows_for_links(df_JDM_r_relation,seedwords):
    df_JDM_r_relation_=df_JDM_r_relation.copy()
    lenght=df_JDM_r_relation_.shape[0]
    for row in range(lenght):
        if (df_JDM_r_relation_.loc[row,"Source"] not in seedwords) or (df_JDM_r_relation_.loc[row,"Destination"] not in seedwords):
            df_JDM_r_relation_=df_JDM_r_relation_.drop(row,axis=0)
        print(row/lenght,"%")
        clear_output(wait=True)
    df_JDM_r_relation_=df_JDM_r_relation_.reset_index(drop=True)
    return(df_JDM_r_relation_)



# df_JDM_r_isa[df_JDM_r_isa["Weight"]>230].to_excel("df_JDM_r_isa_230.xlsx")
# df_JDM_r_hypo[df_JDM_r_hypo["Weight"]>120].to_excel("df_JDM_r_hypo_120.xlsx")
# df_JDM_r_syn[df_JDM_r_syn["Weight"]>84].to_excel("df_JDM_r_syn_84.xlsx")
# df_JDM_r_lieu[df_JDM_r_lieu["Weight"]>60].to_excel("df_JDM_r_lieu_60.xlsx")


df_JDM_nodes_removed=remove_non_related_rows_for_nodes(df_JDM_nodes,seedwords)
df_JDM_r_agent_removed=remove_non_related_rows_for_links(df_JDM_r_agent,seedwords)
df_JDM_r_agent_1_removed=remove_non_related_rows_for_links(df_JDM_r_agent_1,seedwords)
df_JDM_r_lieu_removed=remove_non_related_rows_for_links(df_JDM_r_lieu,seedwords)
df_JDM_r_hypo_removed=remove_non_related_rows_for_links(df_JDM_r_hypo,seedwords)
df_JDM_r_raff_sem_removed=remove_non_related_rows_for_links(df_JDM_r_raff_sem,seedwords)
df_JDM_r_syn_removed=remove_non_related_rows_for_links(df_JDM_r_syn,seedwords)
df_JDM_r_isa_removed=remove_non_related_rows_for_links(df_JDM_r_isa,seedwords)

0.9999739495141584 %

In [179]:
df_JDM_nodes_removed.to_excel("./removed_excels/df_JDM_nodes_removed.xlsx")
df_JDM_r_agent_removed.to_excel("./removed_excels/df_JDM_r_agent_removed.xlsx")
df_JDM_r_agent_1_removed.to_excel("./removed_excels/df_JDM_r_agent_1_removed.xlsx")
df_JDM_r_lieu_removed.to_excel("./removed_excels/df_JDM_r_lieu_removed.xlsx")
df_JDM_r_hypo_removed.to_excel("./removed_excels/df_JDM_r_hypo_removed.xlsx")
df_JDM_r_raff_sem_removed.to_excel("./removed_excels/df_JDM_r_raff_sem_removed.xlsx")
df_JDM_r_syn_removed.to_excel("./removed_excels/df_JDM_r_syn_removed.xlsx")
df_JDM_r_isa_removed.to_excel("./removed_excels/df_JDM_r_isa_removed.xlsx")

In [208]:
df_JDM_all_links = pd.concat([df_JDM_r_agent_removed, df_JDM_r_agent_1_removed,
                          df_JDM_r_lieu_removed, df_JDM_r_hypo_removed,
                          df_JDM_r_raff_sem_removed,df_JDM_r_syn_removed,
                          df_JDM_r_isa_removed])
df_JDM_all_links=df_JDM_all_links.reset_index(drop=True)

df_JDM_all_links.to_excel("./removed_excels/df_JDM_all_links.xlsx")

In [235]:
df_JDM_all_links["Source_Name"]=""
df_JDM_all_links["Destination_Name"]=""
# df_JDM_nodes.set_index('ID',inplace=True)

for row in range(df_JDM_all_links.shape[0]):
        df_JDM_all_links.loc[row,"Source_Name"]=df_JDM_nodes.loc[df_JDM_all_links.loc[row,"Source"],"Name"]
        df_JDM_all_links.loc[row,"Destination_Name"]=df_JDM_nodes.loc[df_JDM_all_links.loc[row,"Destination"],"Name"]  

df_JDM_all_links.to_excel("./removed_excels/df_JDM_all_links.xlsx")

In [298]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 

graph_JDM = nx.DiGraph()

graph_dic=[]
for row in range(len(df_JDM_all_links["ID"])):
    graph_dic.append((df_JDM_all_links["Source_Name"][row],df_JDM_all_links["Destination_Name"][row],df_JDM_all_links["Weight"][row]))
    
graph_JDM.add_weighted_edges_from(graph_dic)

nx.write_gexf(graph_JDM, "graph_JDM.gexf")

In [344]:
import pandas as pd
import numpy as np
import networkx as nx
import node2vec
from gensim.models import Word2Vec

'''
Pipeline for representational learning for all nodes in a graph.
'''

graph_JDM = nx.read_gexf("graph_JDM.gexf")
graph_JDM_words = node2vec.Graph(graph_JDM, True, 1, 1)
graph_JDM_words.preprocess_transition_probs()
walks = graph_JDM_words.simulate_walks(300, 80)

Walk iteration:
1 / 300
2 / 300
3 / 300
4 / 300
5 / 300
6 / 300
7 / 300
8 / 300
9 / 300
10 / 300
11 / 300
12 / 300
13 / 300
14 / 300
15 / 300
16 / 300
17 / 300
18 / 300
19 / 300
20 / 300
21 / 300
22 / 300
23 / 300
24 / 300
25 / 300
26 / 300
27 / 300
28 / 300
29 / 300
30 / 300
31 / 300
32 / 300
33 / 300
34 / 300
35 / 300
36 / 300
37 / 300
38 / 300
39 / 300
40 / 300
41 / 300
42 / 300
43 / 300
44 / 300
45 / 300
46 / 300
47 / 300
48 / 300
49 / 300
50 / 300
51 / 300
52 / 300
53 / 300
54 / 300
55 / 300
56 / 300
57 / 300
58 / 300
59 / 300
60 / 300
61 / 300
62 / 300
63 / 300
64 / 300
65 / 300
66 / 300
67 / 300
68 / 300
69 / 300
70 / 300
71 / 300
72 / 300
73 / 300
74 / 300
75 / 300
76 / 300
77 / 300
78 / 300
79 / 300
80 / 300
81 / 300
82 / 300
83 / 300
84 / 300
85 / 300
86 / 300
87 / 300
88 / 300
89 / 300
90 / 300
91 / 300
92 / 300
93 / 300
94 / 300
95 / 300
96 / 300
97 / 300
98 / 300
99 / 300
100 / 300
101 / 300
102 / 300
103 / 300
104 / 300
105 / 300
106 / 300
107 / 300
108 / 300
109 / 300
110 / 300
111 / 300
112 / 300
113 / 300
114 / 300
115 / 300
116 / 300
117 / 300
118 / 300
119 / 300
120 / 300
121 / 300
122 / 300
123 / 300
124 / 300
125 / 300
126 / 300
127 / 300
128 / 300
129 / 300
130 / 300
131 / 300
132 / 300
133 / 300
134 / 300
135 / 300
136 / 300
137 / 300
138 / 300
139 / 300
140 / 300
141 / 300
142 / 300
143 / 300
144 / 300
145 / 300
146 / 300
147 / 300
148 / 300
149 / 300
150 / 300
151 / 300
152 / 300
153 / 300
154 / 300
155 / 300
156 / 300
157 / 300
158 / 300
159 / 300
160 / 300
161 / 300
162 / 300
163 / 300
164 / 300
165 / 300
166 / 300
167 / 300
168 / 300
169 / 300
170 / 300
171 / 300
172 / 300
173 / 300
174 / 300
175 / 300
176 / 300
177 / 300
178 / 300
179 / 300
180 / 300
181 / 300
182 / 300
183 / 300
184 / 300
185 / 300
186 / 300
187 / 300
188 / 300
189 / 300
190 / 300
191 / 300
192 / 300
193 / 300
194 / 300
195 / 300
196 / 300
197 / 300
198 / 300
199 / 300
200 / 300
201 / 300
202 / 300
203 / 300
204 / 300
205 / 300
206 / 300
207 / 300
208 / 300
209 / 300
210 / 300
211 / 300
212 / 300
213 / 300
214 / 300
215 / 300
216 / 300
217 / 300
218 / 300
219 / 300
220 / 300
221 / 300
222 / 300
223 / 300
224 / 300
225 / 300
226 / 300
227 / 300
228 / 300
229 / 300
230 / 300
231 / 300
232 / 300
233 / 300
234 / 300
235 / 300
236 / 300
237 / 300
238 / 300
239 / 300
240 / 300
241 / 300
242 / 300
243 / 300
244 / 300
245 / 300
246 / 300
247 / 300
248 / 300
249 / 300
250 / 300
251 / 300
252 / 300
253 / 300
254 / 300
255 / 300
256 / 300
257 / 300
258 / 300
259 / 300
260 / 300
261 / 300
262 / 300
263 / 300
264 / 300
265 / 300
266 / 300
267 / 300
268 / 300
269 / 300
270 / 300
271 / 300
272 / 300
273 / 300
274 / 300
275 / 300
276 / 300
277 / 300
278 / 300
279 / 300
280 / 300
281 / 300
282 / 300
283 / 300
284 / 300
285 / 300
286 / 300
287 / 300
288 / 300
289 / 300
290 / 300
291 / 300
292 / 300
293 / 300
294 / 300
295 / 300
296 / 300
297 / 300
298 / 300
299 / 300
300 / 300

In [345]:
# walks = [list(map(str, walk)) for walk in walks]
model = Word2Vec(walks, size=128, window=10, min_count=0, sg=1, workers=8, iter=1)
model.wv.save_word2vec_format("word_embedding_JDM.emd")

In [351]:
model.most_similar("rue")

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.

[('bourg', 0.7688126564025879),
 ('voie', 0.7338396310806274),
 ('quartier', 0.7337194681167603),
 ('hameau', 0.7063071131706238),
 ('rue>215052', 0.704581618309021),
 ('arrondissement', 0.6889646649360657),
 ('entraide', 0.6808754205703735),
 ('village', 0.6585452556610107),
 ('gamelle', 0.6569488048553467),
 ('pharmacie de garde', 0.6553810834884644)]

In [326]:
df_JDM_nodes

                         Name  Type  Weight
ID
61490                   femme     1   29538
74860                   homme     1   28244
124094                 enfant     1   18442
17559                  animal     1   13305
45179                  maison     1   12078
6890                  voiture     1   10998
16033                 cuisine     1   10630
65012                     eau     1   10527
116477               personne     1    9832
130164                 manger     1    9666
70527                 musique     1    9256
146105                    mer     1    8962
136786                  ville     1    8684
130400                maladie     1    7643
91240                   école     1    7412
29592                    film     1    7343
140176                 oiseau     1    7094
144916                 argent     1    6800
37298                   amour     1    6790
142787                  livre     1    6780
24742                  cinéma     1    6674
20564                     rue     1    6673
68467                 poisson     1    6585
145994                 lettre     1    6534
81934                    main     1    6508
102206               médecine     1    6472
122864                   mort     1    6388
43253                  dormir     1    6028
87286                   fruit     1    5887
68439                individu     1    5790
...                       ...   ...     ...
2748              ultraviolet     1      62
2643                 alourdir     1      62
2595                 assoiffé     1      62
2569                      bât     1      62
2359                antisèche     1      62
2218               sorbetière     1      62
2101              brillamment     1      62
2030                Prométhée     1      62
2000                israélite     1      62
1881                  alumine     1      62
1624                 ratonner     1      62
1609              rouscailler     1      62
1545                 baudrier     1      62
1522         être hors de soi     1      62
1484                 brahmane     1      62
1428                décoffrer     1      62
1335                   venger     1      62
1326                  Beckett     1      62
1204    myope comme une taupe     1      62
1099                 casanova     1      62
1020                magasiner     1      62
957                   ébréché     1      62
742            assainissement     1      62
615                    mazout     1      62
540                      Midi     1      62
464                    rachat     1      62
381                   demeuré     1      62
362      Anthémios de Tralles     1      62
16               Maria Callas     1      62
28947            possiblement     1      61

[33074 rows x 3 columns]