In [ ]:
import requests
import bs4
import re
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


graph_JDM= nx.Graph()

config = {
'user': 'mirzapour',
'password': 'mehdim',
'host': 'karadoc.lirmm.fr',
'database': '05012019_rezojdm',
'raise_on_warnings': True
 }

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

# jdm_cursor.execute("SELECT * FROM nodes WHERE (type=1 or type=2) and weight>60 order by weight desc")
# df_JDM_nodes=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Name','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=1 order by weight desc")
# df_JDM_r_raff_sem=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=5 order by weight desc")
# df_JDM_r_syn=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=6 order by weight desc")
# df_JDM_r_isa=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=8 order by weight desc")
# df_JDM_r_hypo=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=15 order by weight desc")
# df_JDM_r_lieu=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=24 order by weight desc")
# df_JDM_r_agent_1=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=26 order by weight desc")
# df_JDM_r_agent=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])



x1=set(df_JDM_r_raff_sem["Source"].unique())
x2=set(df_JDM_r_raff_sem["Destination"].unique())
y1=x1.union(x2)

x1=set(df_JDM_r_syn["Source"].unique())
x2=set(df_JDM_r_syn["Destination"].unique())
y2=x1.union(x2)


x1=set(df_JDM_r_isa["Source"].unique())
x2=set(df_JDM_r_isa["Destination"].unique())
y3=x1.union(x2)


x1=set(df_JDM_r_hypo["Source"].unique())
x2=set(df_JDM_r_hypo["Destination"].unique())
y4=x1.union(x2)


x1=set(df_JDM_r_lieu["Source"].unique())
x2=set(df_JDM_r_lieu["Destination"].unique())
y5=x1.union(x2)


x1=set(df_JDM_r_agent_1["Source"].unique())
x2=set(df_JDM_r_agent_1["Destination"].unique())
y6=x1.union(x2)


x1=set(df_JDM_r_agent["Source"].unique())
x2=set(df_JDM_r_agent["Destination"].unique())
y7=x1.union(x2)

y8=y1.union(y2,y3,y4,y5,y6,y7)

z=set(df_JDM_nodes["ID"].unique())

for id in range(df_JDM_nodes.shape[0]):
    graph_JDM.add_node(df_JDM_nodes.iloc[id]["Name"])
    
    
# nx.write_gexf(graph_JDM, "graph_JDM.gexf")    

# nx.draw(graph_JDM, with_labels = True)
# plt.show()



jdm_db.close()

seed_nodes=list(z.intersection(y8))
seed_nodes.sort()

print(len(y8))
print(len(z))
print(len(z.intersection(y8)))

In [2]:
import requests
import bs4
import re
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


graph_JDM= nx.Graph()

config = {
'user': 'mirzapour',
'password': 'mehdim',
'host': 'karadoc.lirmm.fr',
'database': '05012019_rezojdm',
'raise_on_warnings': True
 }

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

jdm_db = mysql.connector.connect(**config)

jdm_cursor = jdm_db.cursor()

# jdm_cursor.execute("SELECT * FROM nodes WHERE (type=1 or type=2) and weight>60 order by weight desc")
# df_JDM_nodes=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Name','Type','Weight'])
# df_JDM_nodes.to_excel("df_JDM_nodes.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=1 order by weight desc")
# df_JDM_r_raff_sem=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_raff_sem.to_excel("df_JDM_r_raff_sem.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=5 order by weight desc")
# df_JDM_r_syn=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_syn.to_excel("df_JDM_r_syn.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=6 order by weight desc")
# df_JDM_r_isa=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_isa.to_excel("df_JDM_r_isa.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=8 order by weight desc")
# df_JDM_r_hypo=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_hypo.to_excel("df_JDM_r_hypo.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=15 order by weight desc")
# df_JDM_r_lieu=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_lieu.to_excel("df_JDM_r_lieu.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=24 order by weight desc")
# df_JDM_r_agent_1=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_agent_1.to_excel("df_JDM_r_agent_1.xlsx")

# jdm_cursor.execute("SELECT * FROM edges where weight>50 and type=26 order by weight desc")
# df_JDM_r_agent=pd.DataFrame(jdm_cursor.fetchall(),columns=['ID','Source','Destination','Type','Weight'])
# df_JDM_r_agent.to_excel("df_JDM_r_agent.xlsx")

jdm_db.close()

In [85]:
import requests
import bs4
import re
import datetime
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 


df_JDM_nodes=pd.read_excel("df_JDM_nodes.xlsx")
df_JDM_seed_words=pd.read_excel("List_of_Seed_Words_Top_30000.xlsx")
seedwords=list(df_JDM_seed_words["Nodes"])

df_JDM_r_raff_sem=pd.read_excel("df_JDM_r_raff_sem.xlsx")
df_JDM_r_syn=pd.read_excel("df_JDM_r_syn_84.xlsx")
df_JDM_r_isa=pd.read_excel("df_JDM_r_isa_230.xlsx")
df_JDM_r_hypo=pd.read_excel("df_JDM_r_hypo_120.xlsx")
df_JDM_r_lieu=pd.read_excel("df_JDM_r_lieu_60.xlsx")
df_JDM_r_agent_1=pd.read_excel("df_JDM_r_agent_1.xlsx")
df_JDM_r_agent=pd.read_excel("df_JDM_r_agent.xlsx")

In [161]:
from IPython.display import clear_output

def remove_non_related_rows_for_nodes(df_JDM_r_relation,seedwords):
    df_JDM_r_relation_=df_JDM_r_relation.copy()
    lenght=df_JDM_r_relation_.shape[0]
    for row in range(lenght):
        if (df_JDM_r_relation_.loc[row,"ID"] not in seedwords):
            df_JDM_r_relation_=df_JDM_r_relation_.drop(row,axis=0)
        print(row/lenght,"%")
        clear_output(wait=True)
    df_JDM_r_relation_=df_JDM_r_relation_.reset_index(drop=True)
    return(df_JDM_r_relation_)


def remove_non_related_rows_for_links(df_JDM_r_relation,seedwords):
    df_JDM_r_relation_=df_JDM_r_relation.copy()
    lenght=df_JDM_r_relation_.shape[0]
    for row in range(lenght):
        if (df_JDM_r_relation_.loc[row,"Source"] not in seedwords) or (df_JDM_r_relation_.loc[row,"Destination"] not in seedwords):
            df_JDM_r_relation_=df_JDM_r_relation_.drop(row,axis=0)
        print(row/lenght,"%")
        clear_output(wait=True)
    df_JDM_r_relation_=df_JDM_r_relation_.reset_index(drop=True)
    return(df_JDM_r_relation_)



# df_JDM_r_isa[df_JDM_r_isa["Weight"]>230].to_excel("df_JDM_r_isa_230.xlsx")
# df_JDM_r_hypo[df_JDM_r_hypo["Weight"]>120].to_excel("df_JDM_r_hypo_120.xlsx")
# df_JDM_r_syn[df_JDM_r_syn["Weight"]>84].to_excel("df_JDM_r_syn_84.xlsx")
# df_JDM_r_lieu[df_JDM_r_lieu["Weight"]>60].to_excel("df_JDM_r_lieu_60.xlsx")


df_JDM_nodes_removed=remove_non_related_rows_for_nodes(df_JDM_nodes,seedwords)
df_JDM_r_agent_removed=remove_non_related_rows_for_links(df_JDM_r_agent,seedwords)
df_JDM_r_agent_1_removed=remove_non_related_rows_for_links(df_JDM_r_agent_1,seedwords)
df_JDM_r_lieu_removed=remove_non_related_rows_for_links(df_JDM_r_lieu,seedwords)
df_JDM_r_hypo_removed=remove_non_related_rows_for_links(df_JDM_r_hypo,seedwords)
df_JDM_r_raff_sem_removed=remove_non_related_rows_for_links(df_JDM_r_raff_sem,seedwords)
df_JDM_r_syn_removed=remove_non_related_rows_for_links(df_JDM_r_syn,seedwords)
df_JDM_r_isa_removed=remove_non_related_rows_for_links(df_JDM_r_isa,seedwords)

0.9999739495141584 %

In [179]:
df_JDM_nodes_removed.to_excel("./removed_excels/df_JDM_nodes_removed.xlsx")
df_JDM_r_agent_removed.to_excel("./removed_excels/df_JDM_r_agent_removed.xlsx")
df_JDM_r_agent_1_removed.to_excel("./removed_excels/df_JDM_r_agent_1_removed.xlsx")
df_JDM_r_lieu_removed.to_excel("./removed_excels/df_JDM_r_lieu_removed.xlsx")
df_JDM_r_hypo_removed.to_excel("./removed_excels/df_JDM_r_hypo_removed.xlsx")
df_JDM_r_raff_sem_removed.to_excel("./removed_excels/df_JDM_r_raff_sem_removed.xlsx")
df_JDM_r_syn_removed.to_excel("./removed_excels/df_JDM_r_syn_removed.xlsx")
df_JDM_r_isa_removed.to_excel("./removed_excels/df_JDM_r_isa_removed.xlsx")

In [208]:
df_JDM_all_links = pd.concat([df_JDM_r_agent_removed, df_JDM_r_agent_1_removed,
                          df_JDM_r_lieu_removed, df_JDM_r_hypo_removed,
                          df_JDM_r_raff_sem_removed,df_JDM_r_syn_removed,
                          df_JDM_r_isa_removed])
df_JDM_all_links=df_JDM_all_links.reset_index(drop=True)

df_JDM_all_links.to_excel("./removed_excels/df_JDM_all_links.xlsx")

In [235]:
df_JDM_all_links["Source_Name"]=""
df_JDM_all_links["Destination_Name"]=""
# df_JDM_nodes.set_index('ID',inplace=True)

for row in range(df_JDM_all_links.shape[0]):
        df_JDM_all_links.loc[row,"Source_Name"]=df_JDM_nodes.loc[df_JDM_all_links.loc[row,"Source"],"Name"]
        df_JDM_all_links.loc[row,"Destination_Name"]=df_JDM_nodes.loc[df_JDM_all_links.loc[row,"Destination"],"Name"]  

df_JDM_all_links.to_excel("./removed_excels/df_JDM_all_links.xlsx")

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline 

graph_JDM = nx.DiGraph()

graph_dic=[]
for row in range(len(df_JDM_all_links["ID"])):
    graph_dic.append((df_JDM_all_links["Source_Name"][row],df_JDM_all_links["Destination_Name"][row],df_JDM_all_links["Weight"][row]))
    
graph_JDM.add_weighted_edges_from(graph_dic)

nx.write_gexf(graph_JDM, "graph_JDM.gexf")

NameError: name 'df_JDM_all_links' is not defined

In [16]:
import pandas as pd
import numpy as np
import networkx as nx
import node2vec
from gensim.models import Word2Vec

'''
Pipeline for representational learning for all nodes in a graph.
'''

graph_JDM = nx.read_gexf("graph_JDM.gexf")
graph_JDM_words = node2vec.Graph(graph_JDM, True, 1, 1)
graph_JDM_words.preprocess_transition_probs()
walks = graph_JDM_words.simulate_walks(200, 80)

Walk iteration:
1 / 200
2 / 200
3 / 200
4 / 200
5 / 200
6 / 200
7 / 200
8 / 200
9 / 200
10 / 200
11 / 200
12 / 200
13 / 200
14 / 200
15 / 200
16 / 200
17 / 200
18 / 200
19 / 200
20 / 200
21 / 200
22 / 200
23 / 200
24 / 200
25 / 200
26 / 200
27 / 200
28 / 200
29 / 200
30 / 200
31 / 200
32 / 200
33 / 200
34 / 200
35 / 200
36 / 200
37 / 200
38 / 200
39 / 200
40 / 200
41 / 200
42 / 200
43 / 200
44 / 200
45 / 200
46 / 200
47 / 200
48 / 200
49 / 200
50 / 200
51 / 200
52 / 200
53 / 200
54 / 200
55 / 200
56 / 200
57 / 200
58 / 200
59 / 200
60 / 200
61 / 200
62 / 200
63 / 200
64 / 200
65 / 200
66 / 200
67 / 200
68 / 200
69 / 200
70 / 200
71 / 200
72 / 200
73 / 200
74 / 200
75 / 200
76 / 200
77 / 200
78 / 200
79 / 200
80 / 200
81 / 200
82 / 200
83 / 200
84 / 200
85 / 200
86 / 200
87 / 200
88 / 200
89 / 200
90 / 200
91 / 200
92 / 200
93 / 200
94 / 200
95 / 200
96 / 200
97 / 200
98 / 200
99 / 200
100 / 200
101 / 200
102 / 200
103 / 200
104 / 200
105 / 200
106 / 200
107 / 200
108 / 200
109 / 200
110 / 200
111 / 200
112 / 200
113 / 200
114 / 200
115 / 200
116 / 200
117 / 200
118 / 200
119 / 200
120 / 200
121 / 200
122 / 200
123 / 200
124 / 200
125 / 200
126 / 200
127 / 200
128 / 200
129 / 200
130 / 200
131 / 200
132 / 200
133 / 200
134 / 200
135 / 200
136 / 200
137 / 200
138 / 200
139 / 200
140 / 200
141 / 200
142 / 200
143 / 200
144 / 200
145 / 200
146 / 200
147 / 200
148 / 200
149 / 200
150 / 200
151 / 200
152 / 200
153 / 200
154 / 200
155 / 200
156 / 200
157 / 200
158 / 200
159 / 200
160 / 200
161 / 200
162 / 200
163 / 200
164 / 200
165 / 200
166 / 200
167 / 200
168 / 200
169 / 200
170 / 200
171 / 200
172 / 200
173 / 200
174 / 200
175 / 200
176 / 200
177 / 200
178 / 200
179 / 200
180 / 200
181 / 200
182 / 200
183 / 200
184 / 200
185 / 200
186 / 200
187 / 200
188 / 200
189 / 200
190 / 200
191 / 200
192 / 200
193 / 200
194 / 200
195 / 200
196 / 200
197 / 200
198 / 200
199 / 200
200 / 200

In [17]:
# walks = [list(map(str, walk)) for walk in walks]
model = Word2Vec(walks, size=128, window=10, min_count=0, sg=1, workers=8, iter=1)
model.save("word_embedding_JDM.emd")

In [18]:
import node2vec
from gensim.models import Word2Vec,KeyedVectors
from gensim.test.utils import datapath
import gensim

model = KeyedVectors.load('word_embedding_JDM.emd')

model.most_similar("rue")

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).

[('bourg', 0.7868659496307373),
 ('voie', 0.7645117044448853),
 ('hameau', 0.7312285304069519),
 ('quartier', 0.724852442741394),
 ('rue>215052', 0.7172147035598755),
 ('arrondissement', 0.7168128490447998),
 ('quartier>219810', 0.687454342842102),
 ('morceau', 0.6843329668045044),
 ('bourgade', 0.6677708625793457),
 ('commune', 0.663520097732544)]

In [326]:
df_JDM_nodes

                         Name  Type  Weight
ID
61490                   femme     1   29538
74860                   homme     1   28244
124094                 enfant     1   18442
17559                  animal     1   13305
45179                  maison     1   12078
6890                  voiture     1   10998
16033                 cuisine     1   10630
65012                     eau     1   10527
116477               personne     1    9832
130164                 manger     1    9666
70527                 musique     1    9256
146105                    mer     1    8962
136786                  ville     1    8684
130400                maladie     1    7643
91240                   école     1    7412
29592                    film     1    7343
140176                 oiseau     1    7094
144916                 argent     1    6800
37298                   amour     1    6790
142787                  livre     1    6780
24742                  cinéma     1    6674
20564                     rue     1    6673
68467                 poisson     1    6585
145994                 lettre     1    6534
81934                    main     1    6508
102206               médecine     1    6472
122864                   mort     1    6388
43253                  dormir     1    6028
87286                   fruit     1    5887
68439                individu     1    5790
...                       ...   ...     ...
2748              ultraviolet     1      62
2643                 alourdir     1      62
2595                 assoiffé     1      62
2569                      bât     1      62
2359                antisèche     1      62
2218               sorbetière     1      62
2101              brillamment     1      62
2030                Prométhée     1      62
2000                israélite     1      62
1881                  alumine     1      62
1624                 ratonner     1      62
1609              rouscailler     1      62
1545                 baudrier     1      62
1522         être hors de soi     1      62
1484                 brahmane     1      62
1428                décoffrer     1      62
1335                   venger     1      62
1326                  Beckett     1      62
1204    myope comme une taupe     1      62
1099                 casanova     1      62
1020                magasiner     1      62
957                   ébréché     1      62
742            assainissement     1      62
615                    mazout     1      62
540                      Midi     1      62
464                    rachat     1      62
381                   demeuré     1      62
362      Anthémios de Tralles     1      62
16               Maria Callas     1      62
28947            possiblement     1      61

[33074 rows x 3 columns]